Add transaction toasts
solid-world/solid-world-marketplace-frontend pull request #182
Opened 2022-05-17 01:19 UTC by cawabunga

Closes #180 

PR adds a single entry point for transactions representation, so an offer placing and its cancelation look the same.

https://user-images.githubusercontent.com/3716894/168707642-27bf63a8-ea2c-4f54-a3c7-ce251d5ec610.mp4

2022-05-17 12:29 UTC, jeffprestes requested changes

2022-05-17 12:29 UTC, jeffprestes commented on src/components/transactionToast/TransactionLink.tsx
> +  const link = `https://mumbai.polygonscan.com/tx/${transactionHash}`
Maybe here would be good leave the link for the scan system as parameter because it can be changed to Polygon mainnet, Celo or other blockchains.

2022-05-17 17:54 UTC, lucasdcoutinh0 approved these changes

2022-05-18 01:29 UTC, cawabunga commented on src/components/transactionToast/TransactionLink.tsx
> +  const link = `https://mumbai.polygonscan.com/tx/${transactionHash}`
I updated this part. Now the block explorer depends on the network.

2022-05-18 12:42 UTC, jeffprestes approved these changes

2022-05-18 12:42 UTC, merged